language: python

# Cache dependencies between builds
cache: pip

python:
  - "3.6"

# Required by deploy.sh
node_js:
  - "8.7"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - pipenv run python manage.py migrate

script:
  - pipenv run python manage.py test

before_deploy:
  - npm install -g captainduckduck

deploy:
  provider: script
  script: captainduckduck deploy -s -h https://captain.florimondmanca.com -a api -p $CAPTAIN_PASSWORD
  on:
    branch: master

env:
  global:
    secure: "EjwW/cs6st9bQnKmfM+9UcKkkxQ7J+7eL1XXyAZYVvTCFesxURb5VA2iq9V5ABrQ3Jh6KhL1J16B3QGPGqChujENP5NCIANsJpCXtUvrixv2NmwlrKxUffs2ftpSNhadfDd72wujrQjKwEMVXwMdGR3Oh/aI2FZXjVcFqOYDmjfc45ejdcnAVNIKgnsMNSYQazyH6S1JwN00XiiTOCtd6H5F5rehKXNbJ2R/Pw4lQ22pLiRu5B3vlIVY9LInSMncnk76/0MvaFyFlw0HUhEwseZLM4zIcSf4swOqiQ0rd4U96TYUCfRhY86zqXynHpz9RxmITEVi6tyekQmpRbJEiJL4oMikERe1Su1gg7TAtDXBqn//iS5ELzpFNkueaq2f2ZpPu27ODgh6m2eed0Nk0IJuQAGDYd9yi9xCEg+iuqOiPXXWLLtFKAmiACUuNMra3zJdMS31t2y9rL1uNSGAqjCzZSLXHpVhc1hW5NJ9mgdogG6hSicaioc89o8ZGgmm1coJv5nhWTRmJDK/dAtancUC9sN6fJsBceKrulSmnGtHWp7/ksXcg7T04zB8g/pJBpxA9m8ls+5O8Z5EUGnWjGi7wEfTFrefTqNZN/pkClTTR5i/msd57yPzRtteMeqlXFfb2Rug5NCYFwOyMNFcGRyybQ5VXnmJLCmHpsvnLNE="
