language: python

cache: pip

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - openssl aes-256-cbc -K $encrypted_10c95f5eae30_key -iv $encrypted_10c95f5eae30_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d
  - chmod +x .travis/deploy.sh
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy.key
  - ssh-add .travis/deploy.key
  - ssh-keyscan florimond.dev >> ~/.ssh/known_hosts
  - git remote add dokku dokku@florimond.dev:api

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - export DATABASE_URL="postgres://postgres:postgres@localhost:5432/personal"
  - pipenv run python manage.py migrate

script:
  - pipenv run python manage.py test

deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
