language: python

# Cache dependencies between builds
cache: pip

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - pipenv run python manage.py migrate

script:
  - pipenv run python manage.py test

# deploy:
#   provider: heroku
#   app:
#     # only on master
#     master: florimondmanca-api
#   run:
#     # automatically run database migrations
#     - python manage.py migrate
#   api_key:
#     secure: "jg/YYder9ZBJMqo+OOz7VW4EkJN+SNHsJ1NlNDTpZDKGCRFIfm0cDuD0MkXubP/UqU+RgBW89kWm+mvxgtnxJnRUK27PVAwJyHz6BPKDEnT/voY3e6CVyKv7mxHt74/0bUayRPtmnyQFZ/T1pKhynUl70+mdidsXiRfxYm72fhCM3m0oQOihNtB5VIwsRLDNncfnKiLf9EQ/gdh/9Kr5CsaJG7hxdot9CCt41knBVb+UOwasAJ6GXKDAw2rcCjjtp6Z7pCw9+27CO7VE2lYi02IhOf5LsraW86m590H2upLMe/+ax5DWxJBloRucQSdlMN5bikSMeKYGlfnw1SW8RkkYhAzqF5mD1JJ1qiK6UBqUU0QkNMHJadFob3fd0Oaa2S9gskfNozC2ppQYzWUFZwenq/5akrBVvmuKbBCSAE0+1ADjgJhb8jWEseAcnBLXRfjEDFxEwEzq7WXS/s04pipE7+CXbeVB3ovTedFrhInw6z28qzCExBag3oMokV3UxTs3cTe8tIOcjWKngPd7pa/+sCOaFnWx6e70XyIJWkVLMU+TyDU7RchIQ5SXtWHyr/jWJD5tZycPBWcVGx16SpCdjYchzIa3HyY/P8GlVXuO1trtCoQK8JatXZ5UHP2NdzgaAN0hDwMhjZAI5ciPWn/o9ltjqEkdPFHV3Jwq1ew="
