language: python

# Cache dependencies between builds
cache: pip

python:
  - "3.6"

# Required by deploy.sh
node_js:
  - "8.7"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - pipenv run python manage.py migrate

script:
  - pipenv run python manage.py test

before_deploy:
  - npm install -g captainduckduck

deploy:
  provider: script
  script: captainduckduck deploy -h 167.99.84.65 -a api -p $CAPTAIN_PASSWORD
  on:
    branch: master

env:
  global:
    secure: QtwF6NaNx/w9tiZVghkOk8DIxG7I8IwY5e525ivgN3msCiQXWzgXniisos3Y3lovOUoSbH4tbGcuSK+oi8egXV9AdnnvzQjXZ3eHwUuM600o/fRaaxSA63B+IoDqFF8JNMKOvpHNjgPBd78vSbQe5tRO007o58kwNuoQfTv4/NLySfnsQ6C6AXvIHynzv4Rnr+duyms8kk0xNJEOoN6RP8lOCCTj1KmnYbcykFcymVwj8cPcLum90zHtp+mr7W3Qi2Y7xZJMT5PD2efqpcPa5LCvr+0wz9L6wPpAW7i4veHWeeZZcJcf1OroOaK0i4yUl7MBAvCiX7rsjTJSi/jhDeMHNSE0UgVrQqL2D3R/gbc7iguFAp4cGnNTnTPLLLeyK0oY/8rkiWT7EZOFOlagODLVNeZmNQ7yhMRBuwVS1rccnNVxtNAUDKC5L/O1hwJF6vjt5lHTBhYqYvsbbH+K9WWW9bUHStU4DCwJ2cXX9GzKZNWGiqn/P59EgBOOsney5nErowKNRXCy72bgd+ofPeOQdIV1dFaRSztgMNYCv7YVLUv4J+nE4hAYrMAapYSotLhNoJv1F6m/Cz8gcNc2FUr8rWJS23LkprHjeBDS1Z0n9mETVo68HcyoC9JjPGQiC30ILCbX4KMju3INVjxLk4wz3tVDkjDgCbmKqX2tKdA=
