language: python

# Cache dependencies between builds
cache: pip

python:
  - "3.6"

# Required by deploy.sh
node_js:
  - "8.7"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - pipenv run python manage.py migrate

script:
  - pipenv run python manage.py test

before_deploy:
  - npm install -g captainduckduck

deploy:
  provider: script
  script: captainduckduck deploy -s -h 167.99.84.65 -a api -p $CAPTAIN_PASSWORD
  on:
    branch: master

env:
  global:
    secure: "GqYVEqyxstzYld2tc+nfXrGzqwcWyN14jZH2VYK5CJJWk5AEvV1OYd+rkt7xfyKTnMKcLbH3pNTMUcRvb22tGS0KYRYi+RGrvcHFTEvSXW/OlHhmglJAUAPCu9TJ9ek7aO9fr+eoUknRqEtYzjCCPbxC6k0Qdhut0hBopxNJG85Re3ZwR8Mb3k4YbpIc3KWvWIL4Z6zinsA078pxA/v+H+i1A1cJQ6ei8lUYBciDARntU4xpfZ9OpI7evtp/bUEH5QofcdKOmkkH/EpkZg+ZDFvWEgMHqpEy26vbZ4rM4wUbN48ThB9jMVUqzUcDZKPeI4pPhrAbnOlFt785wjlUOLAivGRHcq0TQnolV6grVbmb5It2o9bnxgY0xeYfvZMPO6v8qHK1gYSR7G8yalarIvd3CtRPn2iDuI7TQIc8wDnfoiWFLeGyueCWqGgYjvpPI4QmNjasrbrEuZ4TdPLLUnDib+NE31uukrMbX6rTjFP+i6yLrHtp3ttxjwkhTZw0nEJRzXNUdz9WWxEXBHMotrFukoGUjHljYkRb9pISljhKec2R7c9MEHv3IgN+CtNt/H0HpBm1Fz5ogjIprKqu3/satd9CGfdeEuU+ZRo22NMwJ+uILHRhsmad0bdAkYMPQHVHHcuaixWayNZQUQx3igGvzhcV9gFHoZ9NBZx1oZU="
