language: python

# Cache dependencies between builds
cache: pip

python:
  - "3.6"

# Required by deploy.sh
node_js:
  - "8.7"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - pipenv run python manage.py migrate

script:
  - pipenv run python manage.py test

before_deploy:
  - npm install -g captainduckduck

deploy:
  provider: script
  script: captainduckduck deploy -h 167.99.84.65 -a api -p $CAPTAIN_PASSWORD
  on:
    branch: master

env:
  global:
    secure: "TI90l+hilpLdni7doLZm7WbYtlUycVY9Io9KDdomabe5w/Vkh9PlrIvz6Y6VL9s4o058xtsSqwLljzzZFOy/e95vpjpV/OHUvGNbxhki4Y/aoenrt1hiyx+j3i7qv9FPfhNHEabQx3wKBYv0K4s9Ssra3Eb8y+gY3ld8kuU5vI6IwNQv4sxfl5GHSZFo+8AAnB0UqMbbWawAz4GVpG+SmnBVxye05C3PcQFRO2JHrjVXqkWmDAJyXGOBzHa29gARmtGZ5vPO3Q/6iK6e2Uy01k6PHwk7wNeiviqsBhG2Ylygwj35Co6pFS0nBJcoHWTO1sFvu9o2AyEeYOYNC8YLcW4luvdoFyv75JdXbpBvvmuf9ixw/DHQELQpjgHc4bBUcuinrqHmslaVehaa5rBQEaRcQ1S/Zq490qOjLTJhUsd4hx3eA5leMYAGH3OoLPGYEtAGuo5XZ8BCvvhgPULk3f8JcT4jYGGko57fAEmuSNH+mfzibBbl/T+unJd/sx57aLH1HeBlBMzhuQdFNkHg8UzxN3vSaGnd0Y8Qn/OCaNQY63DO7+EktCHnvHPvFL62bDQzPLZj8ozxVhvtI8G7WFSzMOap48TEHcc+7hHlrl2/IMtIlqFSWV1E9oVmwVN2SyJ/Fo0+6DfHD3mfVWIQaTR77/rqZGf407PYnFVX54M="
