language: python

# Cache dependencies between builds
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/personal

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database personal;' -U postgres
  - python manage.py migrate

script:
  - pipenv run python manage.py test

# TODO
# deploy:
#   # See TravisCI docs: https://docs.travis-ci.com/user/deployment/heroku/
#   provider: heroku
#   app:
#     master: florimondmanca-api
#   run:
#     # automatically run new migrations
#     - 'python manage.py migrate'
#   api_key: TODO
