# Generated by Django 2.0.6 on 2018-06-25 20:46

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField()),
                ("content", markdownx.models.MarkdownxField()),
                ("published", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-published",)},
        )
    ]
