# Generated by Django 2.0.7 on 2018-07-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0006_reaction")]

    operations = [
        migrations.RenameField(
            model_name="reaction", old_name="timestamp", new_name="created"
        )
    ]
