# Generated by Django 2.0.7 on 2018-08-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0009_auto_20180814_1836")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Used for social cards and RSS."
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post-images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
