# Generated by Django 2.0.7 on 2018-09-05 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0010_auto_20180814_1852")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        )
    ]
