# Generated by Django 2.1.1 on 2018-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0013_remove_post_image")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_caption",
            field=models.TextField(blank=True, null=True),
        )
    ]
