# Generated by Django 2.1.2 on 2018-10-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0017_auto_20181020_1516")]

    operations = [migrations.RemoveField(model_name="post", name="tags")]
