# Generated by Django 2.0.7 on 2018-07-07 19:38

import api_key.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(max_length=50, unique=True)),
                ('key', models.CharField(default=api_key.utils.generate_key, max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
            },
        ),
    ]
